/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesWordleRouteImport } from './routes/games/wordle'
import { Route as GamesWordchainRouteImport } from './routes/games/wordchain'
import { Route as GamesTyperaceRouteImport } from './routes/games/typerace'
import { Route as GamesDrawingRouteImport } from './routes/games/drawing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordleRoute = GamesWordleRouteImport.update({
  id: '/games/wordle',
  path: '/games/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordchainRoute = GamesWordchainRouteImport.update({
  id: '/games/wordchain',
  path: '/games/wordchain',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTyperaceRoute = GamesTyperaceRouteImport.update({
  id: '/games/typerace',
  path: '/games/typerace',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDrawingRoute = GamesDrawingRouteImport.update({
  id: '/games/drawing',
  path: '/games/drawing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/drawing': typeof GamesDrawingRoute
  '/games/typerace': typeof GamesTyperaceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/games/wordle': typeof GamesWordleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/drawing': typeof GamesDrawingRoute
  '/games/typerace': typeof GamesTyperaceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/games/wordle': typeof GamesWordleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/drawing': typeof GamesDrawingRoute
  '/games/typerace': typeof GamesTyperaceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/games/wordle': typeof GamesWordleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/drawing'
    | '/games/typerace'
    | '/games/wordchain'
    | '/games/wordle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/drawing'
    | '/games/typerace'
    | '/games/wordchain'
    | '/games/wordle'
  id:
    | '__root__'
    | '/'
    | '/games/drawing'
    | '/games/typerace'
    | '/games/wordchain'
    | '/games/wordle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesDrawingRoute: typeof GamesDrawingRoute
  GamesTyperaceRoute: typeof GamesTyperaceRoute
  GamesWordchainRoute: typeof GamesWordchainRoute
  GamesWordleRoute: typeof GamesWordleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/wordle': {
      id: '/games/wordle'
      path: '/games/wordle'
      fullPath: '/games/wordle'
      preLoaderRoute: typeof GamesWordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/wordchain': {
      id: '/games/wordchain'
      path: '/games/wordchain'
      fullPath: '/games/wordchain'
      preLoaderRoute: typeof GamesWordchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/typerace': {
      id: '/games/typerace'
      path: '/games/typerace'
      fullPath: '/games/typerace'
      preLoaderRoute: typeof GamesTyperaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/drawing': {
      id: '/games/drawing'
      path: '/games/drawing'
      fullPath: '/games/drawing'
      preLoaderRoute: typeof GamesDrawingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesDrawingRoute: GamesDrawingRoute,
  GamesTyperaceRoute: GamesTyperaceRoute,
  GamesWordchainRoute: GamesWordchainRoute,
  GamesWordleRoute: GamesWordleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
